from typing import Protocol, Optional, List, Dict, Any


class IUserRepository(Protocol):
    def get_by_id(self, user_id: str) -> Optional[Any]: ...
    def get_by_email(self, email: str) -> Optional[Any]: ...
    def get_by_username(self, username: str) -> Optional[Any]: ...
    def create_user(self, email: str, username: str, password_hash: str) -> Any: ...
    def update_content_source(self, user_id: str, content_source: Optional[str]) -> Optional[Any]: ...
    def update_avatar(self, user_id: str, avatar_json: str) -> Optional[Any]: ...
    def update_progress(self, user_id: str, progress_json: Optional[str]) -> Optional[Any]: ...
    def list_all(self) -> List[Any]: ...


class ISessionRepository(Protocol):
    def get_by_id(self, session_id: str) -> Optional[Any]: ...
    def get_by_user_id(self, user_id: str) -> Optional[Any]: ...
    def save(self, session_obj: Any) -> Any: ...
    def delete(self, session_id: str) -> bool: ...
    def list_all(self) -> List[Any]: ...


class IAuthRepository(Protocol):
    def create_session(self, user_id: str, token_hash: str, ttl_days: int) -> Any: ...
    def get_session(self, token_hash: str) -> Optional[Any]: ...
    def delete_session(self, token_hash: str) -> bool: ...
    def create_verification_code(self, user_id: str, code_hash: str, ttl_seconds: int) -> Any: ...
    def get_valid_verification_code(self, code_hash: str) -> Optional[Any]: ...
    def mark_code_used(self, code_id: str) -> None: ...
